export interface iRegionOption {
	label: string;
	value: string;
}

export const indonesianRegions: iRegionOption[] = [
	// Aceh
	{ label: "Kabupaten Aceh Barat", value: "Kabupaten Aceh Barat" },
	{ label: "Kabupaten Aceh Barat Daya", value: "Kabupaten Aceh Barat Daya" },
	{ label: "Kabupaten Aceh Besar", value: "Kabupaten Aceh Besar" },
	{ label: "Kabupaten Aceh Jaya", value: "Kabupaten Aceh Jaya" },
	{ label: "Kabupaten Aceh Selatan", value: "Kabupaten Aceh Selatan" },
	{ label: "Kabupaten Aceh Singkil", value: "Kabupaten Aceh Singkil" },
	{ label: "Kabupaten Aceh Tamiang", value: "Kabupaten Aceh Tamiang" },
	{ label: "Kabupaten Aceh Tengah", value: "Kabupaten Aceh Tengah" },
	{ label: "Kabupaten Aceh Tenggara", value: "Kabupaten Aceh Tenggara" },
	{ label: "Kabupaten Aceh Timur", value: "Kabupaten Aceh Timur" },
	{ label: "Kabupaten Aceh Utara", value: "Kabupaten Aceh Utara" },
	{ label: "Kabupaten Bener Meriah", value: "Kabupaten Bener Meriah" },
	{ label: "Kabupaten Bireuen", value: "Kabupaten Bireuen" },
	{ label: "Kabupaten Gayo Lues", value: "Kabupaten Gayo Lues" },
	{ label: "Kabupaten Nagan Raya", value: "Kabupaten Nagan Raya" },
	{ label: "Kabupaten Pidie", value: "Kabupaten Pidie" },
	{ label: "Kabupaten Pidie Jaya", value: "Kabupaten Pidie Jaya" },
	{ label: "Kabupaten Simeulue", value: "Kabupaten Simeulue" },
	{ label: "Kota Banda Aceh", value: "Kota Banda Aceh" },
	{ label: "Kota Langsa", value: "Kota Langsa" },
	{ label: "Kota Lhokseumawe", value: "Kota Lhokseumawe" },
	{ label: "Kota Sabang", value: "Kota Sabang" },
	{ label: "Kota Subulussalam", value: "Kota Subulussalam" },

	// Sumatera Utara
	{ label: "Kabupaten Asahan", value: "Kabupaten Asahan" },
	{ label: "Kabupaten Batubara", value: "Kabupaten Batubara" },
	{ label: "Kabupaten Dairi", value: "Kabupaten Dairi" },
	{ label: "Kabupaten Deli Serdang", value: "Kabupaten Deli Serdang" },
	{ label: "Kabupaten Humbang Hasundutan", value: "Kabupaten Humbang Hasundutan" },
	{ label: "Kabupaten Karo", value: "Kabupaten Karo" },
	{ label: "Kabupaten Labuhanbatu", value: "Kabupaten Labuhanbatu" },
	{ label: "Kabupaten Labuhanbatu Selatan", value: "Kabupaten Labuhanbatu Selatan" },
	{ label: "Kabupaten Labuhanbatu Utara", value: "Kabupaten Labuhanbatu Utara" },
	{ label: "Kabupaten Langkat", value: "Kabupaten Langkat" },
	{ label: "Kabupaten Mandailing Natal", value: "Kabupaten Mandailing Natal" },
	{ label: "Kabupaten Nias", value: "Kabupaten Nias" },
	{ label: "Kabupaten Nias Barat", value: "Kabupaten Nias Barat" },
	{ label: "Kabupaten Nias Selatan", value: "Kabupaten Nias Selatan" },
	{ label: "Kabupaten Nias Utara", value: "Kabupaten Nias Utara" },
	{ label: "Kabupaten Padang Lawas", value: "Kabupaten Padang Lawas" },
	{ label: "Kabupaten Padang Lawas Utara", value: "Kabupaten Padang Lawas Utara" },
	{ label: "Kabupaten Pakpak Bharat", value: "Kabupaten Pakpak Bharat" },
	{ label: "Kabupaten Samosir", value: "Kabupaten Samosir" },
	{ label: "Kabupaten Serdang Bedagai", value: "Kabupaten Serdang Bedagai" },
	{ label: "Kabupaten Simalungun", value: "Kabupaten Simalungun" },
	{ label: "Kabupaten Tapanuli Selatan", value: "Kabupaten Tapanuli Selatan" },
	{ label: "Kabupaten Tapanuli Tengah", value: "Kabupaten Tapanuli Tengah" },
	{ label: "Kabupaten Tapanuli Utara", value: "Kabupaten Tapanuli Utara" },
	{ label: "Kabupaten Toba Samosir", value: "Kabupaten Toba Samosir" },
	{ label: "Kota Binjai", value: "Kota Binjai" },
	{ label: "Kota Gunungsitoli", value: "Kota Gunungsitoli" },
	{ label: "Kota Medan", value: "Kota Medan" },
	{ label: "Kota Padangsidempuan", value: "Kota Padangsidempuan" },
	{ label: "Kota Pematangsiantar", value: "Kota Pematangsiantar" },
	{ label: "Kota Sibolga", value: "Kota Sibolga" },
	{ label: "Kota Tanjungbalai", value: "Kota Tanjungbalai" },
	{ label: "Kota Tebing Tinggi", value: "Kota Tebing Tinggi" },

	// Sumatera Barat
	{ label: "Kabupaten Agam", value: "Kabupaten Agam" },
	{ label: "Kabupaten Dharmasraya", value: "Kabupaten Dharmasraya" },
	{ label: "Kabupaten Kepulauan Mentawai", value: "Kabupaten Kepulauan Mentawai" },
	{ label: "Kabupaten Lima Puluh Kota", value: "Kabupaten Lima Puluh Kota" },
	{ label: "Kabupaten Padang Pariaman", value: "Kabupaten Padang Pariaman" },
	{ label: "Kabupaten Pasaman", value: "Kabupaten Pasaman" },
	{ label: "Kabupaten Pasaman Barat", value: "Kabupaten Pasaman Barat" },
	{ label: "Kabupaten Pesisir Selatan", value: "Kabupaten Pesisir Selatan" },
	{ label: "Kabupaten Sijunjung", value: "Kabupaten Sijunjung" },
	{ label: "Kabupaten Solok", value: "Kabupaten Solok" },
	{ label: "Kabupaten Solok Selatan", value: "Kabupaten Solok Selatan" },
	{ label: "Kabupaten Tanah Datar", value: "Kabupaten Tanah Datar" },
	{ label: "Kota Bukittinggi", value: "Kota Bukittinggi" },
	{ label: "Kota Padang", value: "Kota Padang" },
	{ label: "Kota Padangpanjang", value: "Kota Padangpanjang" },
	{ label: "Kota Pariaman", value: "Kota Pariaman" },
	{ label: "Kota Payakumbuh", value: "Kota Payakumbuh" },
	{ label: "Kota Sawahlunto", value: "Kota Sawahlunto" },
	{ label: "Kota Solok", value: "Kota Solok" },

	// Riau
	{ label: "Kabupaten Bengkalis", value: "Kabupaten Bengkalis" },
	{ label: "Kabupaten Indragiri Hilir", value: "Kabupaten Indragiri Hilir" },
	{ label: "Kabupaten Indragiri Hulu", value: "Kabupaten Indragiri Hulu" },
	{ label: "Kabupaten Kampar", value: "Kabupaten Kampar" },
	{ label: "Kabupaten Kepulauan Meranti", value: "Kabupaten Kepulauan Meranti" },
	{ label: "Kabupaten Kuantan Singingi", value: "Kabupaten Kuantan Singingi" },
	{ label: "Kabupaten Pelalawan", value: "Kabupaten Pelalawan" },
	{ label: "Kabupaten Rokan Hilir", value: "Kabupaten Rokan Hilir" },
	{ label: "Kabupaten Rokan Hulu", value: "Kabupaten Rokan Hulu" },
	{ label: "Kabupaten Siak", value: "Kabupaten Siak" },
	{ label: "Kota Dumai", value: "Kota Dumai" },
	{ label: "Kota Pekanbaru", value: "Kota Pekanbaru" },

	// Jambi
	{ label: "Kabupaten Batanghari", value: "Kabupaten Batanghari" },
	{ label: "Kabupaten Bungo", value: "Kabupaten Bungo" },
	{ label: "Kabupaten Kerinci", value: "Kabupaten Kerinci" },
	{ label: "Kabupaten Merangin", value: "Kabupaten Merangin" },
	{ label: "Kabupaten Muaro Jambi", value: "Kabupaten Muaro Jambi" },
	{ label: "Kabupaten Sarolangun", value: "Kabupaten Sarolangun" },
	{ label: "Kabupaten Tanjung Jabung Barat", value: "Kabupaten Tanjung Jabung Barat" },
	{ label: "Kabupaten Tanjung Jabung Timur", value: "Kabupaten Tanjung Jabung Timur" },
	{ label: "Kabupaten Tebo", value: "Kabupaten Tebo" },
	{ label: "Kota Jambi", value: "Kota Jambi" },
	{ label: "Kota Sungai Penuh", value: "Kota Sungai Penuh" },

	// Sumatera Selatan
	{ label: "Kabupaten Banyuasin", value: "Kabupaten Banyuasin" },
	{ label: "Kabupaten Empat Lawang", value: "Kabupaten Empat Lawang" },
	{ label: "Kabupaten Lahat", value: "Kabupaten Lahat" },
	{ label: "Kabupaten Muara Enim", value: "Kabupaten Muara Enim" },
	{ label: "Kabupaten Musi Banyuasin", value: "Kabupaten Musi Banyuasin" },
	{ label: "Kabupaten Musi Rawas", value: "Kabupaten Musi Rawas" },
	{ label: "Kabupaten Musi Rawas Utara", value: "Kabupaten Musi Rawas Utara" },
	{ label: "Kabupaten Ogan Ilir", value: "Kabupaten Ogan Ilir" },
	{ label: "Kabupaten Ogan Komering Ilir", value: "Kabupaten Ogan Komering Ilir" },
	{ label: "Kabupaten Ogan Komering Ulu", value: "Kabupaten Ogan Komering Ulu" },
	{ label: "Kabupaten Ogan Komering Ulu Selatan", value: "Kabupaten Ogan Komering Ulu Selatan" },
	{ label: "Kabupaten Ogan Komering Ulu Timur", value: "Kabupaten Ogan Komering Ulu Timur" },
	{ label: "Kabupaten Penukal Abab Lematang Ilir", value: "Kabupaten Penukal Abab Lematang Ilir" },
	{ label: "Kota Lubuklinggau", value: "Kota Lubuklinggau" },
	{ label: "Kota Pagar Alam", value: "Kota Pagar Alam" },
	{ label: "Kota Palembang", value: "Kota Palembang" },
	{ label: "Kota Prabumulih", value: "Kota Prabumulih" },

	// Bengkulu
	{ label: "Kabupaten Bengkulu Selatan", value: "Kabupaten Bengkulu Selatan" },
	{ label: "Kabupaten Bengkulu Tengah", value: "Kabupaten Bengkulu Tengah" },
	{ label: "Kabupaten Bengkulu Utara", value: "Kabupaten Bengkulu Utara" },
	{ label: "Kabupaten Kaur", value: "Kabupaten Kaur" },
	{ label: "Kabupaten Kepahiang", value: "Kabupaten Kepahiang" },
	{ label: "Kabupaten Lebong", value: "Kabupaten Lebong" },
	{ label: "Kabupaten Mukomuko", value: "Kabupaten Mukomuko" },
	{ label: "Kabupaten Rejang Lebong", value: "Kabupaten Rejang Lebong" },
	{ label: "Kabupaten Seluma", value: "Kabupaten Seluma" },
	{ label: "Kota Bengkulu", value: "Kota Bengkulu" },

	// Lampung
	{ label: "Kabupaten Lampung Barat", value: "Kabupaten Lampung Barat" },
	{ label: "Kabupaten Lampung Selatan", value: "Kabupaten Lampung Selatan" },
	{ label: "Kabupaten Lampung Tengah", value: "Kabupaten Lampung Tengah" },
	{ label: "Kabupaten Lampung Timur", value: "Kabupaten Lampung Timur" },
	{ label: "Kabupaten Lampung Utara", value: "Kabupaten Lampung Utara" },
	{ label: "Kabupaten Mesuji", value: "Kabupaten Mesuji" },
	{ label: "Kabupaten Pesawaran", value: "Kabupaten Pesawaran" },
	{ label: "Kabupaten Pesisir Barat", value: "Kabupaten Pesisir Barat" },
	{ label: "Kabupaten Pringsewu", value: "Kabupaten Pringsewu" },
	{ label: "Kabupaten Tanggamus", value: "Kabupaten Tanggamus" },
	{ label: "Kabupaten Tulang Bawang", value: "Kabupaten Tulang Bawang" },
	{ label: "Kabupaten Tulang Bawang Barat", value: "Kabupaten Tulang Bawang Barat" },
	{ label: "Kabupaten Way Kanan", value: "Kabupaten Way Kanan" },
	{ label: "Kota Bandar Lampung", value: "Kota Bandar Lampung" },
	{ label: "Kota Metro", value: "Kota Metro" },

	// Kepulauan Bangka Belitung
	{ label: "Kabupaten Bangka", value: "Kabupaten Bangka" },
	{ label: "Kabupaten Bangka Barat", value: "Kabupaten Bangka Barat" },
	{ label: "Kabupaten Bangka Selatan", value: "Kabupaten Bangka Selatan" },
	{ label: "Kabupaten Bangka Tengah", value: "Kabupaten Bangka Tengah" },
	{ label: "Kabupaten Belitung", value: "Kabupaten Belitung" },
	{ label: "Kabupaten Belitung Timur", value: "Kabupaten Belitung Timur" },
	{ label: "Kota Pangkal Pinang", value: "Kota Pangkal Pinang" },

	// Kepulauan Riau
	{ label: "Kabupaten Bintan", value: "Kabupaten Bintan" },
	{ label: "Kabupaten Karimun", value: "Kabupaten Karimun" },
	{ label: "Kabupaten Kepulauan Anambas", value: "Kabupaten Kepulauan Anambas" },
	{ label: "Kabupaten Lingga", value: "Kabupaten Lingga" },
	{ label: "Kabupaten Natuna", value: "Kabupaten Natuna" },
	{ label: "Kota Batam", value: "Kota Batam" },
	{ label: "Kota Tanjung Pinang", value: "Kota Tanjung Pinang" },

	// DKI Jakarta
	{ label: "Kota Jakarta Barat", value: "Kota Jakarta Barat" },
	{ label: "Kota Jakarta Pusat", value: "Kota Jakarta Pusat" },
	{ label: "Kota Jakarta Selatan", value: "Kota Jakarta Selatan" },
	{ label: "Kota Jakarta Timur", value: "Kota Jakarta Timur" },
	{ label: "Kota Jakarta Utara", value: "Kota Jakarta Utara" },

	// Jawa Barat
	{ label: "Kabupaten Bandung", value: "Kabupaten Bandung" },
	{ label: "Kabupaten Bandung Barat", value: "Kabupaten Bandung Barat" },
	{ label: "Kabupaten Bekasi", value: "Kabupaten Bekasi" },
	{ label: "Kabupaten Bogor", value: "Kabupaten Bogor" },
	{ label: "Kabupaten Ciamis", value: "Kabupaten Ciamis" },
	{ label: "Kabupaten Cianjur", value: "Kabupaten Cianjur" },
	{ label: "Kabupaten Cirebon", value: "Kabupaten Cirebon" },
	{ label: "Kabupaten Garut", value: "Kabupaten Garut" },
	{ label: "Kabupaten Indramayu", value: "Kabupaten Indramayu" },
	{ label: "Kabupaten Karawang", value: "Kabupaten Karawang" },
	{ label: "Kabupaten Kuningan", value: "Kabupaten Kuningan" },
	{ label: "Kabupaten Majalengka", value: "Kabupaten Majalengka" },
	{ label: "Kabupaten Pangandaran", value: "Kabupaten Pangandaran" },
	{ label: "Kabupaten Purwakarta", value: "Kabupaten Purwakarta" },
	{ label: "Kabupaten Subang", value: "Kabupaten Subang" },
	{ label: "Kabupaten Sukabumi", value: "Kabupaten Sukabumi" },
	{ label: "Kabupaten Sumedang", value: "Kabupaten Sumedang" },
	{ label: "Kabupaten Tasikmalaya", value: "Kabupaten Tasikmalaya" },
	{ label: "Kota Bandung", value: "Kota Bandung" },
	{ label: "Kota Banjar", value: "Kota Banjar" },
	{ label: "Kota Bekasi", value: "Kota Bekasi" },
	{ label: "Kota Bogor", value: "Kota Bogor" },
	{ label: "Kota Cimahi", value: "Kota Cimahi" },
	{ label: "Kota Cirebon", value: "Kota Cirebon" },
	{ label: "Kota Depok", value: "Kota Depok" },
	{ label: "Kota Sukabumi", value: "Kota Sukabumi" },
	{ label: "Kota Tasikmalaya", value: "Kota Tasikmalaya" },

	// Jawa Tengah
	{ label: "Kabupaten Banjarnegara", value: "Kabupaten Banjarnegara" },
	{ label: "Kabupaten Banyumas", value: "Kabupaten Banyumas" },
	{ label: "Kabupaten Batang", value: "Kabupaten Batang" },
	{ label: "Kabupaten Blora", value: "Kabupaten Blora" },
	{ label: "Kabupaten Boyolali", value: "Kabupaten Boyolali" },
	{ label: "Kabupaten Brebes", value: "Kabupaten Brebes" },
	{ label: "Kabupaten Cilacap", value: "Kabupaten Cilacap" },
	{ label: "Kabupaten Demak", value: "Kabupaten Demak" },
	{ label: "Kabupaten Grobogan", value: "Kabupaten Grobogan" },
	{ label: "Kabupaten Jepara", value: "Kabupaten Jepara" },
	{ label: "Kabupaten Karanganyar", value: "Kabupaten Karanganyar" },
	{ label: "Kabupaten Kebumen", value: "Kabupaten Kebumen" },
	{ label: "Kabupaten Kendal", value: "Kabupaten Kendal" },
	{ label: "Kabupaten Klaten", value: "Kabupaten Klaten" },
	{ label: "Kabupaten Kudus", value: "Kabupaten Kudus" },
	{ label: "Kabupaten Magelang", value: "Kabupaten Magelang" },
	{ label: "Kabupaten Pati", value: "Kabupaten Pati" },
	{ label: "Kabupaten Pekalongan", value: "Kabupaten Pekalongan" },
	{ label: "Kabupaten Pemalang", value: "Kabupaten Pemalang" },
	{ label: "Kabupaten Purbalingga", value: "Kabupaten Purbalingga" },
	{ label: "Kabupaten Purworejo", value: "Kabupaten Purworejo" },
	{ label: "Kabupaten Rembang", value: "Kabupaten Rembang" },
	{ label: "Kabupaten Semarang", value: "Kabupaten Semarang" },
	{ label: "Kabupaten Sragen", value: "Kabupaten Sragen" },
	{ label: "Kabupaten Sukoharjo", value: "Kabupaten Sukoharjo" },
	{ label: "Kabupaten Tegal", value: "Kabupaten Tegal" },
	{ label: "Kabupaten Temanggung", value: "Kabupaten Temanggung" },
	{ label: "Kabupaten Wonogiri", value: "Kabupaten Wonogiri" },
	{ label: "Kabupaten Wonosobo", value: "Kabupaten Wonosobo" },
	{ label: "Kota Magelang", value: "Kota Magelang" },
	{ label: "Kota Pekalongan", value: "Kota Pekalongan" },
	{ label: "Kota Salatiga", value: "Kota Salatiga" },
	{ label: "Kota Semarang", value: "Kota Semarang" },
	{ label: "Kota Surakarta", value: "Kota Surakarta" },
	{ label: "Kota Tegal", value: "Kota Tegal" },

	// DI Yogyakarta
	{ label: "Kabupaten Bantul", value: "Kabupaten Bantul" },
	{ label: "Kabupaten Gunungkidul", value: "Kabupaten Gunungkidul" },
	{ label: "Kabupaten Kulon Progo", value: "Kabupaten Kulon Progo" },
	{ label: "Kabupaten Sleman", value: "Kabupaten Sleman" },
	{ label: "Kota Yogyakarta", value: "Kota Yogyakarta" },

	// Jawa Timur
	{ label: "Kabupaten Bangkalan", value: "Kabupaten Bangkalan" },
	{ label: "Kabupaten Banyuwangi", value: "Kabupaten Banyuwangi" },
	{ label: "Kabupaten Blitar", value: "Kabupaten Blitar" },
	{ label: "Kabupaten Bojonegoro", value: "Kabupaten Bojonegoro" },
	{ label: "Kabupaten Bondowoso", value: "Kabupaten Bondowoso" },
	{ label: "Kabupaten Gresik", value: "Kabupaten Gresik" },
	{ label: "Kabupaten Jember", value: "Kabupaten Jember" },
	{ label: "Kabupaten Jombang", value: "Kabupaten Jombang" },
	{ label: "Kabupaten Kediri", value: "Kabupaten Kediri" },
	{ label: "Kabupaten Lamongan", value: "Kabupaten Lamongan" },
	{ label: "Kabupaten Lumajang", value: "Kabupaten Lumajang" },
	{ label: "Kabupaten Madiun", value: "Kabupaten Madiun" },
	{ label: "Kabupaten Magetan", value: "Kabupaten Magetan" },
	{ label: "Kabupaten Malang", value: "Kabupaten Malang" },
	{ label: "Kabupaten Mojokerto", value: "Kabupaten Mojokerto" },
	{ label: "Kabupaten Nganjuk", value: "Kabupaten Nganjuk" },
	{ label: "Kabupaten Ngawi", value: "Kabupaten Ngawi" },
	{ label: "Kabupaten Pacitan", value: "Kabupaten Pacitan" },
	{ label: "Kabupaten Pamekasan", value: "Kabupaten Pamekasan" },
	{ label: "Kabupaten Pasuruan", value: "Kabupaten Pasuruan" },
	{ label: "Kabupaten Ponorogo", value: "Kabupaten Ponorogo" },
	{ label: "Kabupaten Probolinggo", value: "Kabupaten Probolinggo" },
	{ label: "Kabupaten Sampang", value: "Kabupaten Sampang" },
	{ label: "Kabupaten Sidoarjo", value: "Kabupaten Sidoarjo" },
	{ label: "Kabupaten Situbondo", value: "Kabupaten Situbondo" },
	{ label: "Kabupaten Sumenep", value: "Kabupaten Sumenep" },
	{ label: "Kabupaten Trenggalek", value: "Kabupaten Trenggalek" },
	{ label: "Kabupaten Tuban", value: "Kabupaten Tuban" },
	{ label: "Kabupaten Tulungagung", value: "Kabupaten Tulungagung" },
	{ label: "Kota Batu", value: "Kota Batu" },
	{ label: "Kota Blitar", value: "Kota Blitar" },
	{ label: "Kota Kediri", value: "Kota Kediri" },
	{ label: "Kota Madiun", value: "Kota Madiun" },
	{ label: "Kota Malang", value: "Kota Malang" },
	{ label: "Kota Mojokerto", value: "Kota Mojokerto" },
	{ label: "Kota Pasuruan", value: "Kota Pasuruan" },
	{ label: "Kota Probolinggo", value: "Kota Probolinggo" },
	{ label: "Kota Surabaya", value: "Kota Surabaya" },

	// Banten
	{ label: "Kabupaten Lebak", value: "Kabupaten Lebak" },
	{ label: "Kabupaten Pandeglang", value: "Kabupaten Pandeglang" },
	{ label: "Kabupaten Serang", value: "Kabupaten Serang" },
	{ label: "Kabupaten Tangerang", value: "Kabupaten Tangerang" },
	{ label: "Kota Cilegon", value: "Kota Cilegon" },
	{ label: "Kota Serang", value: "Kota Serang" },
	{ label: "Kota Tangerang", value: "Kota Tangerang" },
	{ label: "Kota Tangerang Selatan", value: "Kota Tangerang Selatan" },

	// Bali
	{ label: "Kabupaten Badung", value: "Kabupaten Badung" },
	{ label: "Kabupaten Bangli", value: "Kabupaten Bangli" },
	{ label: "Kabupaten Buleleng", value: "Kabupaten Buleleng" },
	{ label: "Kabupaten Gianyar", value: "Kabupaten Gianyar" },
	{ label: "Kabupaten Jembrana", value: "Kabupaten Jembrana" },
	{ label: "Kabupaten Karangasem", value: "Kabupaten Karangasem" },
	{ label: "Kabupaten Klungkung", value: "Kabupaten Klungkung" },
	{ label: "Kabupaten Tabanan", value: "Kabupaten Tabanan" },
	{ label: "Kota Denpasar", value: "Kota Denpasar" },

	// Nusa Tenggara Barat
	{ label: "Kabupaten Bima", value: "Kabupaten Bima" },
	{ label: "Kabupaten Dompu", value: "Kabupaten Dompu" },
	{ label: "Kabupaten Lombok Barat", value: "Kabupaten Lombok Barat" },
	{ label: "Kabupaten Lombok Tengah", value: "Kabupaten Lombok Tengah" },
	{ label: "Kabupaten Lombok Timur", value: "Kabupaten Lombok Timur" },
	{ label: "Kabupaten Lombok Utara", value: "Kabupaten Lombok Utara" },
	{ label: "Kabupaten Sumbawa", value: "Kabupaten Sumbawa" },
	{ label: "Kabupaten Sumbawa Barat", value: "Kabupaten Sumbawa Barat" },
	{ label: "Kota Bima", value: "Kota Bima" },
	{ label: "Kota Mataram", value: "Kota Mataram" },

	// Nusa Tenggara Timur
	{ label: "Kabupaten Alor", value: "Kabupaten Alor" },
	{ label: "Kabupaten Belu", value: "Kabupaten Belu" },
	{ label: "Kabupaten Ende", value: "Kabupaten Ende" },
	{ label: "Kabupaten Flores Timur", value: "Kabupaten Flores Timur" },
	{ label: "Kabupaten Kupang", value: "Kabupaten Kupang" },
	{ label: "Kabupaten Lembata", value: "Kabupaten Lembata" },
	{ label: "Kabupaten Malaka", value: "Kabupaten Malaka" },
	{ label: "Kabupaten Manggarai", value: "Kabupaten Manggarai" },
	{ label: "Kabupaten Manggarai Barat", value: "Kabupaten Manggarai Barat" },
	{ label: "Kabupaten Manggarai Timur", value: "Kabupaten Manggarai Timur" },
	{ label: "Kabupaten Nagekeo", value: "Kabupaten Nagekeo" },
	{ label: "Kabupaten Ngada", value: "Kabupaten Ngada" },
	{ label: "Kabupaten Rote Ndao", value: "Kabupaten Rote Ndao" },
	{ label: "Kabupaten Sabu Raijua", value: "Kabupaten Sabu Raijua" },
	{ label: "Kabupaten Sikka", value: "Kabupaten Sikka" },
	{ label: "Kabupaten Sumba Barat", value: "Kabupaten Sumba Barat" },
	{ label: "Kabupaten Sumba Barat Daya", value: "Kabupaten Sumba Barat Daya" },
	{ label: "Kabupaten Sumba Tengah", value: "Kabupaten Sumba Tengah" },
	{ label: "Kabupaten Sumba Timur", value: "Kabupaten Sumba Timur" },
	{ label: "Kabupaten Timor Tengah Selatan", value: "Kabupaten Timor Tengah Selatan" },
	{ label: "Kabupaten Timor Tengah Utara", value: "Kabupaten Timor Tengah Utara" },
	{ label: "Kota Kupang", value: "Kota Kupang" },

	// Kalimantan Barat
	{ label: "Kabupaten Bengkayang", value: "Kabupaten Bengkayang" },
	{ label: "Kabupaten Kapuas Hulu", value: "Kabupaten Kapuas Hulu" },
	{ label: "Kabupaten Kayong Utara", value: "Kabupaten Kayong Utara" },
	{ label: "Kabupaten Ketapang", value: "Kabupaten Ketapang" },
	{ label: "Kabupaten Kubu Raya", value: "Kabupaten Kubu Raya" },
	{ label: "Kabupaten Landak", value: "Kabupaten Landak" },
	{ label: "Kabupaten Melawi", value: "Kabupaten Melawi" },
	{ label: "Kabupaten Mempawah", value: "Kabupaten Mempawah" },
	{ label: "Kabupaten Sambas", value: "Kabupaten Sambas" },
	{ label: "Kabupaten Sanggau", value: "Kabupaten Sanggau" },
	{ label: "Kabupaten Sekadau", value: "Kabupaten Sekadau" },
	{ label: "Kabupaten Sintang", value: "Kabupaten Sintang" },
	{ label: "Kota Pontianak", value: "Kota Pontianak" },
	{ label: "Kota Singkawang", value: "Kota Singkawang" },

	// Kalimantan Tengah
	{ label: "Kabupaten Barito Selatan", value: "Kabupaten Barito Selatan" },
	{ label: "Kabupaten Barito Timur", value: "Kabupaten Barito Timur" },
	{ label: "Kabupaten Barito Utara", value: "Kabupaten Barito Utara" },
	{ label: "Kabupaten Gunung Mas", value: "Kabupaten Gunung Mas" },
	{ label: "Kabupaten Kapuas", value: "Kabupaten Kapuas" },
	{ label: "Kabupaten Katingan", value: "Kabupaten Katingan" },
	{ label: "Kabupaten Kotawaringin Barat", value: "Kabupaten Kotawaringin Barat" },
	{ label: "Kabupaten Kotawaringin Timur", value: "Kabupaten Kotawaringin Timur" },
	{ label: "Kabupaten Lamandau", value: "Kabupaten Lamandau" },
	{ label: "Kabupaten Murung Raya", value: "Kabupaten Murung Raya" },
	{ label: "Kabupaten Pulang Pisau", value: "Kabupaten Pulang Pisau" },
	{ label: "Kabupaten Sukamara", value: "Kabupaten Sukamara" },
	{ label: "Kabupaten Seruyan", value: "Kabupaten Seruyan" },
	{ label: "Kota Palangka Raya", value: "Kota Palangka Raya" },

	// Kalimantan Selatan
	{ label: "Kabupaten Balangan", value: "Kabupaten Balangan" },
	{ label: "Kabupaten Banjar", value: "Kabupaten Banjar" },
	{ label: "Kabupaten Barito Kuala", value: "Kabupaten Barito Kuala" },
	{ label: "Kabupaten Hulu Sungai Selatan", value: "Kabupaten Hulu Sungai Selatan" },
	{ label: "Kabupaten Hulu Sungai Tengah", value: "Kabupaten Hulu Sungai Tengah" },
	{ label: "Kabupaten Hulu Sungai Utara", value: "Kabupaten Hulu Sungai Utara" },
	{ label: "Kabupaten Kotabaru", value: "Kabupaten Kotabaru" },
	{ label: "Kabupaten Tabalong", value: "Kabupaten Tabalong" },
	{ label: "Kabupaten Tanah Bumbu", value: "Kabupaten Tanah Bumbu" },
	{ label: "Kabupaten Tanah Laut", value: "Kabupaten Tanah Laut" },
	{ label: "Kabupaten Tapin", value: "Kabupaten Tapin" },
	{ label: "Kota Banjarbaru", value: "Kota Banjarbaru" },
	{ label: "Kota Banjarmasin", value: "Kota Banjarmasin" },

	// Kalimantan Timur
	{ label: "Kabupaten Berau", value: "Kabupaten Berau" },
	{ label: "Kabupaten Kutai Barat", value: "Kabupaten Kutai Barat" },
	{ label: "Kabupaten Kutai Kartanegara", value: "Kabupaten Kutai Kartanegara" },
	{ label: "Kabupaten Kutai Timur", value: "Kabupaten Kutai Timur" },
	{ label: "Kabupaten Mahakam Ulu", value: "Kabupaten Mahakam Ulu" },
	{ label: "Kabupaten Paser", value: "Kabupaten Paser" },
	{ label: "Kabupaten Penajam Paser Utara", value: "Kabupaten Penajam Paser Utara" },
	{ label: "Kota Balikpapan", value: "Kota Balikpapan" },
	{ label: "Kota Bontang", value: "Kota Bontang" },
	{ label: "Kota Samarinda", value: "Kota Samarinda" },

	// Kalimantan Utara
	{ label: "Kabupaten Bulungan", value: "Kabupaten Bulungan" },
	{ label: "Kabupaten Malinau", value: "Kabupaten Malinau" },
	{ label: "Kabupaten Nunukan", value: "Kabupaten Nunukan" },
	{ label: "Kabupaten Tana Tidung", value: "Kabupaten Tana Tidung" },
	{ label: "Kota Tarakan", value: "Kota Tarakan" },

	// Sulawesi Utara
	{ label: "Kabupaten Bolaang Mongondow", value: "Kabupaten Bolaang Mongondow" },
	{ label: "Kabupaten Bolaang Mongondow Selatan", value: "Kabupaten Bolaang Mongondow Selatan" },
	{ label: "Kabupaten Bolaang Mongondow Timur", value: "Kabupaten Bolaang Mongondow Timur" },
	{ label: "Kabupaten Bolaang Mongondow Utara", value: "Kabupaten Bolaang Mongondow Utara" },
	{ label: "Kabupaten Kepulauan Sangihe", value: "Kabupaten Kepulauan Sangihe" },
	{ label: "Kabupaten Kepulauan Siau Tagulandang Biaro", value: "Kabupaten Kepulauan Siau Tagulandang Biaro" },
	{ label: "Kabupaten Kepulauan Talaud", value: "Kabupaten Kepulauan Talaud" },
	{ label: "Kabupaten Minahasa", value: "Kabupaten Minahasa" },
	{ label: "Kabupaten Minahasa Selatan", value: "Kabupaten Minahasa Selatan" },
	{ label: "Kabupaten Minahasa Tenggara", value: "Kabupaten Minahasa Tenggara" },
	{ label: "Kabupaten Minahasa Utara", value: "Kabupaten Minahasa Utara" },
	{ label: "Kota Bitung", value: "Kota Bitung" },
	{ label: "Kota Kotamobagu", value: "Kota Kotamobagu" },
	{ label: "Kota Manado", value: "Kota Manado" },
	{ label: "Kota Tomohon", value: "Kota Tomohon" },

	// Sulawesi Tengah
	{ label: "Kabupaten Banggai", value: "Kabupaten Banggai" },
	{ label: "Kabupaten Banggai Kepulauan", value: "Kabupaten Banggai Kepulauan" },
	{ label: "Kabupaten Banggai Laut", value: "Kabupaten Banggai Laut" },
	{ label: "Kabupaten Buol", value: "Kabupaten Buol" },
	{ label: "Kabupaten Donggala", value: "Kabupaten Donggala" },
	{ label: "Kabupaten Morowali", value: "Kabupaten Morowali" },
	{ label: "Kabupaten Morowali Utara", value: "Kabupaten Morowali Utara" },
	{ label: "Kabupaten Parigi Moutong", value: "Kabupaten Parigi Moutong" },
	{ label: "Kabupaten Poso", value: "Kabupaten Poso" },
	{ label: "Kabupaten Sigi", value: "Kabupaten Sigi" },
	{ label: "Kabupaten Tojo Una-Una", value: "Kabupaten Tojo Una-Una" },
	{ label: "Kabupaten Toli-Toli", value: "Kabupaten Toli-Toli" },
	{ label: "Kota Palu", value: "Kota Palu" },

	// Sulawesi Selatan
	{ label: "Kabupaten Bantaeng", value: "Kabupaten Bantaeng" },
	{ label: "Kabupaten Barru", value: "Kabupaten Barru" },
	{ label: "Kabupaten Bone", value: "Kabupaten Bone" },
	{ label: "Kabupaten Bulukumba", value: "Kabupaten Bulukumba" },
	{ label: "Kabupaten Enrekang", value: "Kabupaten Enrekang" },
	{ label: "Kabupaten Gowa", value: "Kabupaten Gowa" },
	{ label: "Kabupaten Jeneponto", value: "Kabupaten Jeneponto" },
	{ label: "Kabupaten Kepulauan Selayar", value: "Kabupaten Kepulauan Selayar" },
	{ label: "Kabupaten Luwu", value: "Kabupaten Luwu" },
	{ label: "Kabupaten Luwu Timur", value: "Kabupaten Luwu Timur" },
	{ label: "Kabupaten Luwu Utara", value: "Kabupaten Luwu Utara" },
	{ label: "Kabupaten Maros", value: "Kabupaten Maros" },
	{ label: "Kabupaten Pangkajene dan Kepulauan", value: "Kabupaten Pangkajene dan Kepulauan" },
	{ label: "Kabupaten Pinrang", value: "Kabupaten Pinrang" },
	{ label: "Kabupaten Sidenreng Rappang", value: "Kabupaten Sidenreng Rappang" },
	{ label: "Kabupaten Sinjai", value: "Kabupaten Sinjai" },
	{ label: "Kabupaten Soppeng", value: "Kabupaten Soppeng" },
	{ label: "Kabupaten Takalar", value: "Kabupaten Takalar" },
	{ label: "Kabupaten Tana Toraja", value: "Kabupaten Tana Toraja" },
	{ label: "Kabupaten Toraja Utara", value: "Kabupaten Toraja Utara" },
	{ label: "Kabupaten Wajo", value: "Kabupaten Wajo" },
	{ label: "Kota Makassar", value: "Kota Makassar" },
	{ label: "Kota Palopo", value: "Kota Palopo" },
	{ label: "Kota Parepare", value: "Kota Parepare" },

	// Sulawesi Tenggara
	{ label: "Kabupaten Bombana", value: "Kabupaten Bombana" },
	{ label: "Kabupaten Buton", value: "Kabupaten Buton" },
	{ label: "Kabupaten Buton Selatan", value: "Kabupaten Buton Selatan" },
	{ label: "Kabupaten Buton Tengah", value: "Kabupaten Buton Tengah" },
	{ label: "Kabupaten Buton Utara", value: "Kabupaten Buton Utara" },
	{ label: "Kabupaten Kolaka", value: "Kabupaten Kolaka" },
	{ label: "Kabupaten Kolaka Timur", value: "Kabupaten Kolaka Timur" },
	{ label: "Kabupaten Kolaka Utara", value: "Kabupaten Kolaka Utara" },
	{ label: "Kabupaten Konawe", value: "Kabupaten Konawe" },
	{ label: "Kabupaten Konawe Kepulauan", value: "Kabupaten Konawe Kepulauan" },
	{ label: "Kabupaten Konawe Selatan", value: "Kabupaten Konawe Selatan" },
	{ label: "Kabupaten Konawe Utara", value: "Kabupaten Konawe Utara" },
	{ label: "Kabupaten Muna", value: "Kabupaten Muna" },
	{ label: "Kabupaten Muna Barat", value: "Kabupaten Muna Barat" },
	{ label: "Kabupaten Wakatobi", value: "Kabupaten Wakatobi" },
	{ label: "Kota Bau-Bau", value: "Kota Bau-Bau" },
	{ label: "Kota Kendari", value: "Kota Kendari" },

	// Gorontalo
	{ label: "Kabupaten Boalemo", value: "Kabupaten Boalemo" },
	{ label: "Kabupaten Bone Bolango", value: "Kabupaten Bone Bolango" },
	{ label: "Kabupaten Gorontalo", value: "Kabupaten Gorontalo" },
	{ label: "Kabupaten Gorontalo Utara", value: "Kabupaten Gorontalo Utara" },
	{ label: "Kabupaten Pohuwato", value: "Kabupaten Pohuwato" },
	{ label: "Kota Gorontalo", value: "Kota Gorontalo" },

	// Sulawesi Barat
	{ label: "Kabupaten Majene", value: "Kabupaten Majene" },
	{ label: "Kabupaten Mamasa", value: "Kabupaten Mamasa" },
	{ label: "Kabupaten Mamuju", value: "Kabupaten Mamuju" },
	{ label: "Kabupaten Mamuju Tengah", value: "Kabupaten Mamuju Tengah" },
	{ label: "Kabupaten Pasangkayu", value: "Kabupaten Pasangkayu" },
	{ label: "Kabupaten Polewali Mandar", value: "Kabupaten Polewali Mandar" },

	// Maluku
	{ label: "Kabupaten Buru", value: "Kabupaten Buru" },
	{ label: "Kabupaten Buru Selatan", value: "Kabupaten Buru Selatan" },
	{ label: "Kabupaten Kepulauan Aru", value: "Kabupaten Kepulauan Aru" },
	{ label: "Kabupaten Maluku Barat Daya", value: "Kabupaten Maluku Barat Daya" },
	{ label: "Kabupaten Maluku Tengah", value: "Kabupaten Maluku Tengah" },
	{ label: "Kabupaten Maluku Tenggara", value: "Kabupaten Maluku Tenggara" },
	{ label: "Kabupaten Maluku Tenggara Barat", value: "Kabupaten Maluku Tenggara Barat" },
	{ label: "Kabupaten Seram Bagian Barat", value: "Kabupaten Seram Bagian Barat" },
	{ label: "Kabupaten Seram Bagian Timur", value: "Kabupaten Seram Bagian Timur" },
	{ label: "Kota Ambon", value: "Kota Ambon" },
	{ label: "Kota Tual", value: "Kota Tual" },

	// Maluku Utara
	{ label: "Kabupaten Halmahera Barat", value: "Kabupaten Halmahera Barat" },
	{ label: "Kabupaten Halmahera Tengah", value: "Kabupaten Halmahera Tengah" },
	{ label: "Kabupaten Halmahera Timur", value: "Kabupaten Halmahera Timur" },
	{ label: "Kabupaten Halmahera Selatan", value: "Kabupaten Halmahera Selatan" },
	{ label: "Kabupaten Halmahera Utara", value: "Kabupaten Halmahera Utara" },
	{ label: "Kabupaten Kepulauan Sula", value: "Kabupaten Kepulauan Sula" },
	{ label: "Kabupaten Pulau Morotai", value: "Kabupaten Pulau Morotai" },
	{ label: "Kabupaten Pulau Taliabu", value: "Kabupaten Pulau Taliabu" },
	{ label: "Kota Ternate", value: "Kota Ternate" },
	{ label: "Kota Tidore Kepulauan", value: "Kota Tidore Kepulauan" },

	// Papua Barat
	{ label: "Kabupaten Fakfak", value: "Kabupaten Fakfak" },
	{ label: "Kabupaten Kaimana", value: "Kabupaten Kaimana" },
	{ label: "Kabupaten Manokwari", value: "Kabupaten Manokwari" },
	{ label: "Kabupaten Manokwari Selatan", value: "Kabupaten Manokwari Selatan" },
	{ label: "Kabupaten Maybrat", value: "Kabupaten Maybrat" },
	{ label: "Kabupaten Raja Ampat", value: "Kabupaten Raja Ampat" },
	{ label: "Kabupaten Sorong", value: "Kabupaten Sorong" },
	{ label: "Kabupaten Sorong Selatan", value: "Kabupaten Sorong Selatan" },
	{ label: "Kabupaten Tambrauw", value: "Kabupaten Tambrauw" },
	{ label: "Kabupaten Teluk Bintuni", value: "Kabupaten Teluk Bintuni" },
	{ label: "Kabupaten Teluk Wondama", value: "Kabupaten Teluk Wondama" },
	{ label: "Kota Sorong", value: "Kota Sorong" },

	// Papua
	{ label: "Kabupaten Asmat", value: "Kabupaten Asmat" },
	{ label: "Kabupaten Biak Numfor", value: "Kabupaten Biak Numfor" },
	{ label: "Kabupaten Boven Digoel", value: "Kabupaten Boven Digoel" },
	{ label: "Kabupaten Deiyai", value: "Kabupaten Deiyai" },
	{ label: "Kabupaten Dogiyai", value: "Kabupaten Dogiyai" },
	{ label: "Kabupaten Intan Jaya", value: "Kabupaten Intan Jaya" },
	{ label: "Kabupaten Jayapura", value: "Kabupaten Jayapura" },
	{ label: "Kabupaten Jayawijaya", value: "Kabupaten Jayawijaya" },
	{ label: "Kabupaten Keerom", value: "Kabupaten Keerom" },
	{ label: "Kabupaten Kepulauan Yapen", value: "Kabupaten Kepulauan Yapen" },
	{ label: "Kabupaten Lanny Jaya", value: "Kabupaten Lanny Jaya" },
	{ label: "Kabupaten Mamberamo Raya", value: "Kabupaten Mamberamo Raya" },
	{ label: "Kabupaten Mamberamo Tengah", value: "Kabupaten Mamberamo Tengah" },
	{ label: "Kabupaten Mappi", value: "Kabupaten Mappi" },
	{ label: "Kabupaten Merauke", value: "Kabupaten Merauke" },
	{ label: "Kabupaten Mimika", value: "Kabupaten Mimika" },
	{ label: "Kabupaten Nabire", value: "Kabupaten Nabire" },
	{ label: "Kabupaten Nduga", value: "Kabupaten Nduga" },
	{ label: "Kabupaten Paniai", value: "Kabupaten Paniai" },
	{ label: "Kabupaten Pegunungan Bintang", value: "Kabupaten Pegunungan Bintang" },
	{ label: "Kabupaten Puncak", value: "Kabupaten Puncak" },
	{ label: "Kabupaten Puncak Jaya", value: "Kabupaten Puncak Jaya" },
	{ label: "Kabupaten Sarmi", value: "Kabupaten Sarmi" },
	{ label: "Kabupaten Supiori", value: "Kabupaten Supiori" },
	{ label: "Kabupaten Tolikara", value: "Kabupaten Tolikara" },
	{ label: "Kabupaten Waropen", value: "Kabupaten Waropen" },
	{ label: "Kabupaten Yahukimo", value: "Kabupaten Yahukimo" },
	{ label: "Kabupaten Yalimo", value: "Kabupaten Yalimo" },
	{ label: "Kota Jayapura", value: "Kota Jayapura" },
];
