import Header from "@/components/Header";
import TopHeader from "@/components/TopHeader";
import "./globals.css";
import { Inter, Quicksand } from "next/font/google";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const quick = Quicksand({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  display: "swap",
  variable: "--font-quicksand",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${quick.variable} font-inter`}
        suppressHydrationWarning={true}
      >
        <TopHeader />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
